[API]
key = "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"#"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" # stary API KEY: "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"
assistant_id= "asst_xk3b06hJYYDdoKEZJ9d3AwJC" #"asst_uugyiLY3UMdsUyx8jthuOAXh" # stary ID: "asst_7qMNLJTJstsMYbSPOgIDcYBC"
assistant_id4 = "asst_xDSBmaYEfsfsAXggOgrzWUFs"
assistant_id3 = "asst_jz5iH1XmLmGaABgwcMAc3RyK"
[Mail]
sender_passwords = "mjrq njqw iqey wvpw"
user_mail="slawek.piela@koios-mail.pl"
[Engines]
GPT4="gpt-4-1106-preview"
[Airtable]
airtable_token='patHsYphQcJdpBZpt.05dd09b691daceaa3c5863c058b9bc64d57ef3cc7ce0682005d763c1195a5f5b'
base_id = 'appf2mEcl5QQqAuQe'
table_id = 'tblLMOlghOXtc9ri8'
table_id2 = 'tblPCZOLIe07M92Bb'
[AWS]
aws_access_key_id="AKIAZ2GINTHTPL63TUEL"
aws_secret_access_key="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"
[APISA]
api_sa_key= '4c69408e-ebf0-4f24-8e17-8139c9048066'
api_sa_secret='99b91725-137a-4b7e-bd07-2e730b097adc'

[WHEREBY]
api_key= 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmFwcGVhci5pbiIsImF1ZCI6Imh0dHBzOi8vYXBpLmFwcGVhci5pbi92MSIsImV4cCI6OTAwNzE5OTI1NDc0MDk5MSwiaWF0IjoxNzA2OTg2MDAwLCJvcmdhbml6YXRpb25JZCI6MjEwNDk3LCJqdGkiOiJmYTAwNmM3OC05YmIwLTQxNDUtOWVhOS0wZmM1ODQ3YmZiYmMifQ.SHHx4OSSr6he5bzA1oGA0z91zE06r_JQB2_qBh9AMYI'

[TinyURL]
tiny_api_key='SlEbijC55PDpig1JDsuvEEm7B1KYLepmhfxkGD6599Wp3fnMHBBSFpoCsDV1'